name: Test Runner
on:
  workflow_dispatch:
  
jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      - name: Run Tests
        uses: actions/checkout@v3.3.0
      - name: Install Dependencies
        run: |
          npm install
      - name: Build
        run: |
          node-gyp rebuild
          npm run test
    
